### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by RobLoach** [regisb/reveal.js-fullscreen-img#6]
As of the latest version of Reveal.js, this plugin is no longer needed. Would be great to stick a note on the project page somewhere.

**Comment by Lesik** [comment]
@RobLoach Could you please elaborate why exactly it is not needed? Are you suggesting to use `data-background` instead?

**Comment by RobLoach** [comment]
Yes, I think using `data-background-image`:
https://github.com/hakimel/reveal.js/#image-backgrounds

**Comment by regisb** [comment]
@robloach you are absolutely right. I missed your message from 4 years ago, will post a note.

**Comment by RobLoach** [comment]
Wow, it's been 4 years! 😮 🍰 👍
